AllCops:
  Exclude:
      - vendor/**/*
      - exe/**/*
      - Gemfile*
      - Rakefile
      - '*.gemspec'
  NewCops: enable
  TargetRubyVersion: 2.6

Layout/HashAlignment:
  Enabled: false

Layout/LineLength:
  Max: 150

Layout/MultilineMethodCallIndentation:
  Enabled: false
