source 'https://rubygems.org'

gem 'ffi'
gem 'jekyll', '~> 4.2.2'
gem 'nokogumbo', '=2.0.3'
gem 'ptools'
gem 'sprockets'
gem 'webrick'

group :jekyll_plugins do
  gem 'classifier-reborn'
  gem 'html-proofer'
  gem 'jekyll-assets'
  gem 'jekyll-environment-variables'
  gem 'jekyll_href'
  gem 'jekyll_plugin_logger'
  gem 'jekyll_quote', path: '../'
  gem 'jekyll-tagging'
end

gem 'debase', '0.2.5.beta2', require: false
gem 'ruby-debug-ide', require: false
