source 'https://rubygems.org'

gem 'jekyll', '~> 4.3.2'
gem 'nokogumbo', '=2.0.3'
gem 'ptools'

group :jekyll_plugins do
  gem 'classifier-reborn'
  gem 'html-proofer'
  gem 'jekyll-assets'
  gem 'jekyll-environment-variables'
  gem 'jekyll_href'
  gem 'jekyll_img'
  gem 'jekyll_quote', path: '../'
  gem 'jekyll-tagging'
end

gem 'debase', '0.2.5.beta2', require: false
gem 'ruby-debug-ide', require: false
